# Generated by Django 4.2.24 on 2025-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_fcaba7_idx',
            old_name='expenses_ex_categor_20264a_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='custom_category',
            field=models.CharField(blank=True, help_text="Required when category is 'Others'", max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fuel Expenses', 'Fuel Expenses'), ('Meals', 'Meals'), ('Car Payments', 'Car Payments'), ('Insurance', 'Insurance'), ('Car Maintenance', 'Car Maintenance'), ('Car Repair', 'Car Repair'), ('Legal Fines', 'Legal Fines'), ('Others', 'Others')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
