# Generated by Django 4.2.24 on 2025-10-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_unique_together_remove_category_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='additional_comments',
        ),
    ]
